esphome:
  name: d1-temp
  friendly_name: d1 temp

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "75vdQSOBhEBMBfHkJagjgVazQvyd1rQBO1wBfMhMKCQ="

ota:
  password: "2742221773ec2434814de4ebb1c79edc"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "D1-Temp Fallback Hotspot"
    password: "3dClzDmmhF3i"

time:
  - platform: homeassistant
    id: homeassistant_time

font:
  - file: "gfonts://Roboto"
    id: roboto
    size: 25
  - file: "gfonts://Caveat"
    id: caveat
    size: 25  

# OLED Display     
i2c:
  sda: D2
  scl: D1
  frequency: 800kHz #for current bug 20230903
display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x64"
    address: 0x3C    
    lambda: |-
      it.strftime(id(homeassistant_time).now().second/2, 0, id(roboto), "%H:%M:%S", id(homeassistant_time).now());
      it.printf(id(homeassistant_time).now().second/4, 32, id(caveat), "%.1f° %.0f%%", id(Temperature).state, id(Humidity).state);

binary_sensor:
  # motion Sensor
  - platform: gpio
    pin: D7
    name: "PIR Sensor"
    device_class: motion
    filters:
      - delayed_off: 5s #cover lockout time
    on_press:
      then:
        light.turn_on: LED
    on_release:
      then:
        light.turn_off: LED  

  # light Sensor
  - platform: gpio
    pin: D3
    name: "light Sensor"
    device_class: light
    filters:
      - invert
    on_press:
      then:
        light.turn_off: Onboard_LED
    on_release:
      then:
        light.turn_on: Onboard_LED      

sensor:
  # Temp/Humid sensor
  - platform: dht
    model: AM2302
    pin: D5
    temperature:
      name: "Temperature"
      id: "Temperature"
      accuracy_decimals: 1
    humidity:
      name: "Humidity"
      id: "Humidity"
      accuracy_decimals: 1
    update_interval: 60s    

  # Wifi Signal
  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    name: "WiFi Signal dB"
    id: wifi_signal_db
    update_interval: 300s
    entity_category: "diagnostic"
    internal: true
  - platform: copy # Reports the WiFi signal strength in %
    source_id: wifi_signal_db
    name: "WiFi Signal Percent"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "%"
    entity_category: "diagnostic" 

  # Wifi IP address
text_sensor:
  - platform: wifi_info
    ip_address:
      name: ESP IP Address
      update_interval: 1h
      entity_category: "diagnostic"
    ssid:
      name: ESP Connected SSID
      update_interval: 1h
      entity_category: "diagnostic"
    bssid:
      name: ESP Connected BSSID
      update_interval: 1h
      entity_category: "diagnostic"
#    scan_results:
#      name: ESP Latest Scan Results
#      update_interval: 1h
#      entity_category: "diagnostic"
#    dns_address:
#      name: ESP DNS Address
#      update_interval: 1h
#      entity_category: "diagnostic"

output:
    # external led
  - id: light_output
    platform: gpio
    pin: D0

light:
  # external led
  - platform: binary
    name: "LED"
    id: LED
    output: light_output
    effects:
      - strobe:
          name: Slow Flash        
          colors:
            - state: True
              duration: 500ms
            - state: False
              duration: 500ms
      - strobe:
          name: Fast Flash
          colors:
            - state: True
              duration: 200ms
            - state: False
              duration: 200ms
    
  # Onboard LED
  - platform: status_led
    name: "Onboard LED"
    id: "Onboard_LED"
    pin: 
      number: GPIO2
      inverted: true
    effects:
      - strobe:
          name: Slow Flash        
          colors:
            - state: True
              duration: 500ms
            - state: False
              duration: 500ms
      - strobe:
          name: Fast Flash
          colors:
            - state: True
              duration: 200ms
            - state: False
              duration: 200ms

captive_portal:
    